//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Console.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the backup (Ctrl+C)..
        /// </summary>
        internal static string BackupCancel {
            get {
                return ResourceManager.GetString("BackupCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save completed successfully..
        /// </summary>
        internal static string BackupCompleted {
            get {
                return ResourceManager.GetString("BackupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving failed !.
        /// </summary>
        internal static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the backup name..
        /// </summary>
        internal static string BackupName {
            get {
                return ResourceManager.GetString("BackupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the backup..
        /// </summary>
        internal static string BackupStart {
            get {
                return ResourceManager.GetString("BackupStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error in the backup selection..
        /// </summary>
        internal static string BackupStrategyError {
            get {
                return ResourceManager.GetString("BackupStrategyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup success..
        /// </summary>
        internal static string BackupSucess {
            get {
                return ResourceManager.GetString("BackupSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the backup type..
        /// </summary>
        internal static string BackupTypeSelect {
            get {
                return ResourceManager.GetString("BackupTypeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave console initialized with base path.
        /// </summary>
        internal static string ConsoleInitialized {
            get {
                return ResourceManager.GetString("ConsoleInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential backup..
        /// </summary>
        internal static string DifferentialBackup {
            get {
                return ResourceManager.GetString("DifferentialBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing jobs.
        /// </summary>
        internal static string ExecutingJobs {
            get {
                return ResourceManager.GetString("ExecutingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full backup..
        /// </summary>
        internal static string FullBackup {
            get {
                return ResourceManager.GetString("FullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language..
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory.
        /// </summary>
        internal static string SourceDirectory {
            get {
                return ResourceManager.GetString("SourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory.
        /// </summary>
        internal static string TargetDirectory {
            get {
                return ResourceManager.GetString("TargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a number between 1 and 3..
        /// </summary>
        internal static string UsageHint {
            get {
                return ResourceManager.GetString("UsageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: EasySave.exe &lt;jobIds&gt; (e.g., 1-3 or 1;3;5).
        /// </summary>
        internal static string UsageJob {
            get {
                return ResourceManager.GetString("UsageJob", resourceCulture);
            }
        }
    }
}
