//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Console.Resources.Strings.fr", typeof(Strings_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler la sauvegarde..
        /// </summary>
        internal static string BackupCancel {
            get {
                return ResourceManager.GetString("BackupCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sauvegarde est termninée..
        /// </summary>
        internal static string BackupCompleted {
            get {
                return ResourceManager.GetString("BackupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de sauvegarde !.
        /// </summary>
        internal static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir le nom de la sauvegarde..
        /// </summary>
        internal static string BackupName {
            get {
                return ResourceManager.GetString("BackupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer la sauvegarde..
        /// </summary>
        internal static string BackupStart {
            get {
                return ResourceManager.GetString("BackupStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a une erreur dans le choix de la sauvegarde..
        /// </summary>
        internal static string BackupStrategyError {
            get {
                return ResourceManager.GetString("BackupStrategyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le type de sauvegarde..
        /// </summary>
        internal static string BackupTypeSelect {
            get {
                return ResourceManager.GetString("BackupTypeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Créer un travail de sauvegarde ===.
        /// </summary>
        internal static string CreateJobTitle {
            get {
                return ResourceManager.GetString("CreateJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde différentielle..
        /// </summary>
        internal static string DifferentialBackup {
            get {
                return ResourceManager.GetString("DifferentialBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde complète..
        /// </summary>
        internal static string FullBackup {
            get {
                return ResourceManager.GetString("FullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave - Système de gestion de sauvegarde
        ///
        ///Options :
        ///  1. Créer un travail de sauvegarde - Ajouter une nouvelle configuration de sauvegarde
        ///  2. Lister les travaux - Afficher tous les travaux de sauvegarde configurés
        ///  3. Lancer des sauvegardes - Exécuter un ou plusieurs travaux de sauvegarde
        ///  4. Aide - Afficher ce message d&apos;aide
        ///  0. Quitter - Quitter l&apos;application
        ///
        ///Lors de l&apos;exécution de sauvegardes, vous pouvez spécifier les IDs des travaux comme suit :
        ///  - ID unique : 1
        ///  - Plage : 1-3
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Aide ===.
        /// </summary>
        internal static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée invalide..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travail {0} créé avec succès..
        /// </summary>
        internal static string JobCreated {
            get {
                return ResourceManager.GetString("JobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Travaux de sauvegarde ===.
        /// </summary>
        internal static string ListJobsTitle {
            get {
                return ResourceManager.GetString("ListJobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre maximum de travaux (5) atteint. Impossible de créer plus de travaux..
        /// </summary>
        internal static string MaxJobsReached {
            get {
                return ResourceManager.GetString("MaxJobsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choix invalide. Veuillez sélectionner 1-4 ou 0 pour quitter..
        /// </summary>
        internal static string MenuInvalidChoice {
            get {
                return ResourceManager.GetString("MenuInvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string MenuOption0 {
            get {
                return ResourceManager.GetString("MenuOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un travail de sauvegarde.
        /// </summary>
        internal static string MenuOption1 {
            get {
                return ResourceManager.GetString("MenuOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lister les travaux.
        /// </summary>
        internal static string MenuOption2 {
            get {
                return ResourceManager.GetString("MenuOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer des sauvegardes.
        /// </summary>
        internal static string MenuOption3 {
            get {
                return ResourceManager.GetString("MenuOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        internal static string MenuOption4 {
            get {
                return ResourceManager.GetString("MenuOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre choix :.
        /// </summary>
        internal static string MenuPrompt {
            get {
                return ResourceManager.GetString("MenuPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Menu EasySave ===.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun travail de sauvegarde trouvé..
        /// </summary>
        internal static string NoJobsFound {
            get {
                return ResourceManager.GetString("NoJobsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur une touche pour continuer....
        /// </summary>
        internal static string PressKeyContinue {
            get {
                return ResourceManager.GetString("PressKeyContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Lancer des sauvegardes ===.
        /// </summary>
        internal static string RunJobsTitle {
            get {
                return ResourceManager.GetString("RunJobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez les IDs des travaux à exécuter (ex. : 1-3 ou 1,3,5) :.
        /// </summary>
        internal static string SelectJobsPrompt {
            get {
                return ResourceManager.GetString("SelectJobsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner la langue..
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire source.
        /// </summary>
        internal static string SourceDirectory {
            get {
                return ResourceManager.GetString("SourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire cible.
        /// </summary>
        internal static string TargetDirectory {
            get {
                return ResourceManager.GetString("TargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez selectionner un chiffre allant de 1 à 3..
        /// </summary>
        internal static string UsageHint {
            get {
                return ResourceManager.GetString("UsageHint", resourceCulture);
            }
        }
    }
}
